Repository retaildevcrews/imdb, pull requests merged in 2020-03, with the labels that each got.

#32 Add composite index
  README.md
  data/actors.json
  data/movies.json
  index.json
  src/Program.cs
Labels: IMDb

#33 update CI files to fix incorrect repo name
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.yml
Labels: Bug, IMDb, Pri1, size: S

#36 update cicd to publish to latest tag on merge to master and beta tag …
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.yml
  README.md
  src/Program.cs
Labels: IMDb, Pri1, size: S
