Repository retaildevcrews/imdb, pull requests merged in 2020-02, with the labels that each got.

#26 updated templates from helium
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/checkpoint.md
  .github/ISSUE_TEMPLATE/designreview.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/retro.md
  .github/ISSUE_TEMPLATE/survey.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: IMDb

#28 imdb - Design Template Update
  .github/ISSUE_TEMPLATE/designreview.md
Labels: Bug, Pri1

#29 Updated Standard Templates (Bug, Task, Release, DoD, Feature)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/checkpoint.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/task.md
Labels: Documentation, IMDb, Pri1

#30 Update CI files and Badge on README
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.old
  .github/workflows/dockerCI.yml
  README.md
Labels: Documentation, IMDb, Pri1, size: S
