Repository retaildevcrews/imdb, pull requests merged in 2020-04, with the labels that each got.

#37 update CI to tag image with beta or latest
  .github/workflows/dockerCI.yml
Labels: IMDb, Pri1, size: S

#39 Update Release Template
  .github/ISSUE_TEMPLATE/release.md
Labels: Documentation, Pri1

#40 Updated version and assemblies
  .github/workflows/dockerByPR.yml
  .github/workflows/dockerCI.old
  src/imdb-import.csproj
Labels: IMDb

#41 Update namespace to CSE.ImdbImport
  src/Program.cs
  src/imdb-import.csproj
Labels: IMDb

#42 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation
